package redbacks.robot;

import redbacks.arachne.lib.trajectories.Path;

/**
 * Generated by FRC 4613 - Barker Redbacks' trajectory generator.
 * Any edits to this file will be overwritten when you generate more paths.
 *
 * @author Sean Zammit
 */
public class PathListLucas2
{
	public static Path
